# spring message property
---
spring:
  messages:
    basename: messages/messages
    encoding: UTF-8

# server
server:
  tomcat:
    uri-encoding: UTF-8

# current profile
---
spring:
  profiles:
    active: local

# local profile
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: "jdbc:mariadb://rocker211.asuscomm.com:42802/j3dev"
    username: "root"
    password: "j3dev1234!"
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB10Dialect
        format_sql: true


